export const BRAINFUCK_EXEC_COMPLETE = "BRAINFUCK_EXEC_COMPLETE"
export const BRAINFUCK_EXEC_INCOMPLETE = "BRAINFUCK_EXEC_INCOMPLETE"
export const BRAINFUCK_EXEC_IO_PAUSE = "BRAINFUCK_EXEC_IO_PAUSE"
export const BRAINFUCK_EXEC_ERR = "BRAINFUCK_EXEC_ERR"
export const BRAINFUCK_SET_INPUT_CHAR = "BRAINFUCK_SET_INPUT_CHAR";

export const ABC_EXEC_COMPLETE = "ABC_EXEC_COMPLETE"

export const DEADSIMPLE_EXEC_COMPLETE = "DEADSIMPLE_EXEC_COMPLETE"
export const DEADSIMPLE_EXEC_ERR = "DEADSIMPLE_EXEC_ERR"

export const CORTLANG_EXEC_ERR = "CORTLANG_EXEC_ERR";
export const CORTLANG_EXEC_COMPLETE = "CORTLANG_EXEC_COMPLETE";
export const CORTLANG_EXEC_IO_PAUSE = "CORTLANG_EXEC_IO_PAUSE";
export const CORTLANG_EXEC_INCOMPLETE = "CORTLANG_EXEC_INCOMPLETE";

export const ALPHABETA_EXEC_COMPLETE = "ALPHABETA_EXEC_COMPLETE";
export const ALPHABETA_IO_PAUSE = "ALPHABETA_IO_PAUSE";
export const ALPHABETA_SET_INPUT_CHAR = "ALPHABETA_SET_INPUT_CHAR";
export const ALPHABETA_SET_INPUT_CHAR_J = "ALPHABETA_SET_INPUT_CHAR_J";
export const ALPHABETA_SET_INPUT_CHAR_K = "ALPHABETA_SET_INPUT_CHAR_K";

export const STDOUT_UPDATE = "STDOUT_UPDATE";
export const SOURCE_CODE_BUF_UPDATE = "SOURCE_CODE_BUF_UPDATE";
export const RESET_APP_STATE = "RESET_APP_STATE";
export const SELECTED_LANG_SET = "SELECTED_LANG_SET";